language: nix
sudo: false
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs

env:
  global:
    - # Environment variables for BINTRAY Deployment
    - secure: "gxVUpGDYncltQIQb5+hYQMh0T7E3TrMk8FzXaHvAflGt8bMvSRtd5Dj3bwzObAf7eqgCw0lFrU8uu38ta2JKzuFkkhgo1i4v6b/4yN59dJ2Jxda6cJLlG39apaG+a6QzDxnol0WImuOSgXwYUwmosltt87So0vsvFDoPR25UKAkh83SfSfNnuzOG7raMxMCrHDSjv+eraj8QVLtIScgU+IfJ+9vlOUbggEsLj7ASqgrCk2e6vcSmtwHz4da06xP75lvXQVJDjviHgXFhwNi8q1DE1dFq47Ug0yQInbVkKgZUoil6IJIHlkRFiqng9IzTlH7F60td18wlPlzry3OtbFhrDs7cJOm0QlfHtM/HnukcQZMCzpX80S0DBYwv4Nzv0QlQRlPVmK2q4rEGQ6Or7leNrB/nc9wePw73qo+Q4JsAbrZfMYfn17RByvnSJ0mLVkFdZ7LN6PnvxRK5lRAyz+s2lpxG0GdBEHivQmQotylaxdi+xz4HJJS4YvJu1uaRc93TLT6yaSb6EKwQq4lBfZ5wCcgla3dJKkEYbC2Ge/+sVHQEuU19xnlemtwmo/63LFesY1RMVrpOmjaJ4g4z5OYRz3+M1EYQN+EyIO5X14wBMT59PtA913K9k5So6NT8vWWW8Dq7XxtA4peLMWWJdgsQldxt81kNlqkyjE2DkCo="
    - secure: "LUzO7ur3tTTdgFgGbqMWGvHSPR47g9VaDDV6tFc4SEOTbybkH0oUi93L5UySTynLhNUIz+8mCbaP1GWQ3tOicYlEgXDrjLBcqGOWQo6l9eFWBdLaWlYBR8jnuXOY4aozfw3/ypoDosEMfvI+PiJKxjrOv10jGM5CL/8QpQvM3YQfetTVI6usYSdU/7IoI8xAlx19v6p+AzVP8QAVVpnqQ5dNfYCTztuXwpfOZ+HSugvMV/alMsTxDU3Yzowz11Jcw9t+naFIq+0XY7vKZU2nf8XWHsuoAntfUwVYqQrkSzt+5HpJCEMWWZ7CKMNQmOaC2j6j3/7j+pN4d0lDQO9escuFGnrq93nXvnIoTMqVkMOlk2P7aniqB3xE9QQPTrVzph8ckBi1j+2kKswaYFIXyxRnb3MtdcpqEFq0HJXNeXycbtj9smy0vzDoKT9p69GUJdZ0IZHBQMlcVB7Gr5243k2qxpzi2knQtqZJfjy0kRLsrsdFY8IRnSJXsvVpeKt2Cbqgc1UPMF7FGdrs2MeDFxIHwb+Zi67EoxvRjdEysDdwX1F7FODakU/FDmFe5idBcx4YxKM9l9E8my2K5lQLEu5lig9QcBKn64A2mgwP3n9/8pievskD8/V6xUeyqDTRK89fYMBplieiurKhigAoIYUNiNL69gsnmrDCcouy7Yk="
    - # Environment variables for GITHUB
    - secure: "VO1hfmQ/6G5STqsfjKUR5AAWP1HCNVM/Y3/8MayZPnZhQk/67fl64+94NI+ntekf/M20jZHCUgK7Q8tHjj3+k3DAQ3PcCU0R4YbPQjO9AP+Lfqk+6e76KLdz/4nXN97lyfh28VmJOs5zgcNGIAg+00mi9vSdmfTtufqwE+JQXEZ+7L0aV3Fxic8ORQehwh+ovtffSmVhg+FswEyf1Um6BKnYrs4W8qAS8SCZecmI1e4oiq/Sy3AjyUA0XUdgT6brws1+Ej4gUP1mgCPAjeG6bxyFD86d4yMfnfk79oAa6U0jX22EmT5/vDikIPTjes4jaK9wfaLONIvABSyanCBM1nNNxOF5HfpVT1b1ehQClhwc2ggyABIdJEHNL2gsGEkapPvZAVqHpJIC3lvd0WnGcYCuEejR3Zs09evenz2nFhFmAM0OuBA9rYg+x2qCSjWiUxx+MHP81esfdYn295wPXdSu9gA25HBvbsa4Ull8SfUyJAyx8sTIyUq2GphHWOOaVynSpUQpG/9RGikMBG5fYH3n6k0R2N+7D5oujGYdA3zshlcKOwLat8zdDythAtfSRjwOhM4OrA31dcSzVcUIZSCLCP1giaxPLDpIImrGPWqzvjeJTkZcJDQrpLHcqd4KqBD6YiGm0jNj0X4+T40yoC1DXykd3E9LUC40/IG/boI="
    - secure: "SyqBqayfVJS8POsoWOVHiWPeShZZ/nZE+L4lFozC6KtJGGGf46SrG07GPN7tMdXLmW8PpVC0snpkMZBC1f+zV7s3kRDPI9+okNpDL2MoUyiF7MIwYnGtS+8QzYVnjpk+t1ibZhS6YE7Y1r6HZ/qSagE7XsUDFOthBOkHt/1TnflrZrJNr7IwGFKBuXu1An8Bq7N5u4IuokjsAnL0dvrwH1oLomOaSG2FYHTge1u7aPefY1cDTyUz75EcQnfNnU1Vp7zWFn9X1Q0CcnKPQCsByTq4kL8uH77Yc1dWE49pIbXTGyJj20qnokVtNqD7boUqIL/vlMbeEQyz9RpM5rdlftBihi2f1eUj17kDUnA8wq9L+W2nzIW4QsExwG8EWgyxgmgBKLjKTSQOzkLg5Q6cKChQUdBjHvo+WClkAF2R3BSfSsenfymbOap49pyf2IExoK9CK6J4IZh79ohEJnyRA9rbwNlAV+KVGZCCbGB0/iXI9jzYt4/yKYiC+sjqaV4QYeXICIacN+JetXiL6Yulor9Z9Ej9rD2EcolNfx1R2ZW4s4l10BgzRSYHM0Eq4LWg/nheomD0vJLbMD4KsOPu4/+CeHg4Fxh9KEZ4L4/3IFtoBfR0eza3OAEiyhKEcUSK5YhTS92nBrWGUBAKCRMBv+7HedYPSG9lRfCTIcYNLeI="

script:
  - nix-shell --command "./gradlew assemble check install"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - nix-shell --command "./.travis-publishOnRelease.sh"
